In [2]:
# 문제 1
# 크기 10인 Null 벡터를 생성하되, 다섯 번째 값은 1으로 하는 벡터를 출력하라.
# 단, 데이터 값 타입은 int32로 지정하라.
import numpy as np
vec = np.zeros(10, dtype = 'int32')
vec[4] = 1
print(vec)

[0 0 0 0 1 0 0 0 0 0]


In [3]:
# 문제 2
# 8 * 8 행렬을 생성하여 체크보드 패턴으로 채우라.
# 자세한 형태는 아래와 같다.
# 0 1 0 1 0 1 ..
# 1 0 1 0 1 0 ..
# 0 1 0 1 0 1 ..
vec = np.zeros((8, 8), dtype = 'int32')
vec[1::2, ::2] = 1
vec[::2, 1::2] = 1
print(vec)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
# 문제 3
# 0 ~ 24로 이루어진 배열을 5 * 5 크기로 변환한 후 해당 배열의 1행과 2행을 바꾸어라.
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [23]:
# 문제 4
# 아래의 a 배열을 열 방향으로 기준으로 정렬하라.
a = np.random.randint(0, 10, (3, 3)) # 0 ~ 10 사이의 숫자에서 랜덤추출한 (3, 3) 배열
print(a)
print(np.sort(a, axis = 1))

[[0 5 8]
 [2 5 1]
 [3 8 5]]
[[0 5 8]
 [1 2 5]
 [3 5 8]]


In [24]:
# 문제 5
# X 행렬이 아래와 같을 때 행렬 인덱싱을 사용하여 4의 배수만을 선택하라.
X = np.array([[1,1,1,1], [1,2,4,8], [1,3,5,7],[1,4,16,32],[1,5,9,13]])
X[X % 4 == 0]

array([ 4,  8,  4, 16, 32])